name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - mewlua/main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - mewlua/main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Spell Check Repo
      uses: crate-ci/typos@master

  reformat:
    name: Code Style Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Cache Rust build
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: test
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run style check
      run: pre-commit run --all --hook-stage manual

  clippy:
    name: Clippy Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Rust toolchain with clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Cache Rust build
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: test
    - name: Run Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test
      - name: Run Tests
        run: cargo test --workspace --all-features
